### ISSUE TITLE
old version of jmxtrans?

### ISSUE THREAD

**Issue by lookfirst** [bryanwb/chef-jmxtrans#1]
https://github.com/bryanwb/chef-jmxtrans/blob/master/attributes/default.rb#L5

**Comment by bryanwb** [comment]
is there a newer version I should use?

to get a newer version do I have to compile from source?

On Sun, Jul 22, 2012 at 7:53 AM, Jon Stevens <
reply@reply.github.com

**Comment by lookfirst** [comment]
https://github.com/lookfirst/jmxtrans/downloads

**Comment by bryanwb** [comment]
fixed in this commit https://github.com/bryanwb/chef-jmxtrans/commit/bd480088e1a92120d8917beae9fb142cc6359091

tks!
